✨ .internal 편집 기능 추가
wafflestudio/csereal-web pull request #231
Opened 2024-07-04 09:00 UTC by Limchansol

- `.internal` 페이지 api 연결
  - 내용 `GET`으로 받아오기
  - 편집 기능 추가
- `BasicEditor` 새로 구현
  - 기존에 있던 에디터 관련 컴포넌트 최대한 재사용 및 구조 통일
    - 추후에 `EditorFieldset`이나 버튼 컴포넌트들 `common`으로 분리해도 될 것 같음
  - 다만 `PostEditor`를 가져다 쓰기에는 리팩토링 작업이 복잡해질 것 같아서 간단한 페이지 편집용 `BasicEditor` 새로 구현 
  - 인터널 페이지는 `description`만 있는 페이지라서 다른 페이지들 작업할 때 메인 이미지와 첨부파일 관련된 부분 추가할 예정
- `edit` 페이지를 따로 안 파고 state로 관리하는 중인데, edit 페이지 별개로 파는 게 나을지...?
  - 편집할 부분이 복잡하진 않아서 일단 편집 모드 on/off 하는 방식으로 구현해둠 
- 행정실에서만 쓸 간단한 페이지라서 버튼들은 적당한 곳에 대강 넣음
- 린트 에러 중 `no-unused-var` 때문에 커밋이 불가능해서 그것만 `warn`으로 변경

2024-07-04 11:09 UTC, yeolyi requested changes

2024-07-04 11:09 UTC, yeolyi commented on components/editor/common/ActionButtons.tsx
> +  showDelete = true,
`<EditActionButtons/>`랑 `<EditActionButtons showDelete/>`가 동작이 같아서 헷갈릴 것 같은데, `showDelete` 대신 `hideDelete`는 어때?

2024-07-04 11:09 UTC, yeolyi commented on components/editor/common/ActionButtons.tsx
> +  showDelete = true,
근데 지금 프롭 타입으로는 `showDelete`가 `true`인데 `onDelete`가 없는등 invalid한 상태가 가능한데 차라리 `showDelete`를 없애고 `onDelete`의 존재 유무로 삭제 버튼을 보여줄지 말지 판단하는게 더 깔끔할듯

2024-07-04 11:10 UTC, yeolyi commented
edit 페이지 state로 관리하는거는 괜찮을듯? 다른 쪽 편집 페이지는 기획/디자인이랑 얘기해봐야겠지만 `.internal`은 개발 편의대로 해도 괜찮을거같음

2024-07-04 12:58 UTC, Limchansol commented on app/.internal/page.tsx
> +import React from 'react';
이거 안 들어가면 계속 빨간줄 뜨는데 그게 더 보기 싫어서 넣어둠!

2024-07-04 12:59 UTC, Limchansol commented on actions/internal.ts
> +  }
엇 이거 아마 소식탭쪽이랑 어드민 참고해서 그대로 넣었을 텐데 일단 다시 봐볼게

2024-07-04 13:00 UTC, yeolyi commented on .eslintrc.json
> +    "@typescript-eslint/no-unused-vars": "warn",
`[state, setState]`에서 `[state]`로만 바꾸면 되는거 아니야?

2024-07-04 13:01 UTC, Limchansol commented on components/editor/common/ActionButtons.tsx
> +  showDelete = true,
하이드 쓰면 이중 부정 들어가서 별로이기도 하고 PostEditor인가 옵션들 네이밍이 다 show 어쩌고라 저렇게 해둠! 근데 아예 없애고 딜리트 함수로만 판단하면 될듯?

2024-07-04 13:02 UTC, Limchansol commented on .eslintrc.json
> +    "@typescript-eslint/no-unused-vars": "warn",
아 ㅇㅋㅇㅋ

2024-07-04 13:03 UTC, yeolyi commented on app/.internal/page.tsx
> +import React from 'react';
뭐라고 빨간줄 뜨는데? 폴더 이름이 `.`으로 시작해서 그런건가,,, 나도 import쪽에 빨간줄뜨긴하는데 리액트랑은 관련 없을 것 같아서 그래

2024-07-05 12:16 UTC, Limchansol commented on app/.internal/page.tsx
> +import React from 'react';
각종 컴포넌트랑 태그에 `React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts` 이거 계속 떴는데 지금은 또 지워도 안 뜸... 폴더 이름 `.`으로 시작해서 뜨던 것도 지금은 다시 사라짐 뭐지... 아무튼 지워뒀습니다

2024-07-07 06:29 UTC, yeolyi approved these changes
고생했어~~!~!

2024-07-07 06:56 UTC, merged